CourseWork
KalimullinIlnaz/AndroidLessons pull request #10
Opened 2020-05-28 15:06 UTC by KalimullinIlnaz

Добавлены гуглкарты
Добавлен обратный геокодинг с помощью сервиса Яндекса
В качестве сетевого транспорта используется Retrofit + OkHttp
В качестве сериализации/десериализации JSON используется Gson
Полученная информация сохраняется в БД (ORM Room)
Имеется возможность просмотра сохраненных контактов и их детальной информации.(Должно быть уже реализовано в рамках текущих ДЗ)
Имеется возможность просмотра местоположения контакта на карте в виде пина
Имеется возможность просмотра всех пинов на карте, отмасшатбированной, чтобы влезли все
Задание на выбор ещё не реализовано. Дизайн изменю.

2020-05-28 17:52 UTC, goblinr requested changes

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +    private AppDatabase database;
Этих вещей не должно быть в фрагменте. Это нарушение принципа единственной ответственности. Теперь у тебя класс фрагмента ответственен за:
1. Отображение и взаимодействие с пользовательским интерфейсом
2. Работу с БД
3. Работу с геокодером
4. Плюс еще работа с картой сюда затесалась.

Нужно рефакторить.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +    private AppDatabase database;
Работу с БД - вынести в репозиторий.
Работу с геокодером - в отдельный репозиторий геокодера.
Карту вынести на отдельный экран со своим презентором.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +                new Thread(new Runnable() {
Утечка памяти через анонимный класс `Runnable`
Анонимный класс содержит ссылку на фрагмент.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +        new Thread(new Runnable() {
Утечка памяти через анонимный класс. 
Анонимный класс содержит ссылку на фрагмент.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +                        .enqueue(new Callback<Address>() {
Утечка памяти через анонимный класс.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +                                new Thread(new Runnable() {
Утечка памяти через анонимный класс

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +        getActivity().runOnUiThread(new Runnable() {
Это плохо, если `setMarker` вызывается в цикле(а выше ты делаешь это) - это приводит к появлению большого количества сообщений на Looper главного потока.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
>  public class Contact {
В эту структуру данных, тебе нужно добавить адрес и геопозицию. Заполнять их в репозитории контактов путем получения этих данных из БД. Т.е. основные данные заполняются как и прежде из поставщика контактов, а дополнительные - из БД приложения.

2020-05-28 17:52 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +    <fragment
Карту вытащить в отдельный экран

2020-05-31 16:50 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +    <fragment
Для карты с маркером у конкретного контакта и карты со всеми маркерами использовать один и тот же фрагмент?

2020-05-31 16:54 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +    <fragment
Можно использовать один фрагмент, тогда нужно будет внутри этого фрагмента разруливать логику для этих 2-х кейсов. Но с точки зрения SOLID -  это плохо, поэтому лучше сделать 2 фрагмента.

2020-05-31 17:09 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +    private AppDatabase database;
В БД репозитории в методе на новом потоке получаются данные из поставщика контактов и  бд, после записываются в "контакт" который возвращается из метода и получается в презентере мапФрагмента. Так как метод возвращает какое то значение получается проблемно как то, я пытался сделать через callable и future, но как то не успешно, также, как я понимаю, можно сделать через callback-и, но методов много и как то нагромождено получится.
Есть ли какой то более оптимальный способ?Я читал про RxJava там есть удобные методы для работы с потоками... возможно стоит использовать ее?

2020-05-31 17:31 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +    private AppDatabase database;
Не совсем понял первую часть проблемы. Возможно нужно как-то на примерах объяснить чтоб до меня дошло.

По поводу RxJava - это будет ваше следующее ДЗ.

2020-06-06 21:26 UTC, KalimullinIlnaz commented
"Вариант 1:Имеется возможность проверки, есть ли наземный маршрут между двумя контактами"
Это значит полностью исключить варианты переправы на пароме и т.п?Я пока что просто задаю, в запросе mode = walking

2020-06-06 21:29 UTC, KalimullinIlnaz commented
И как хранить api ключи в проекте?

2020-06-06 22:19 UTC, KalimullinIlnaz commented
Revert случайно сделал

2020-06-07 09:34 UTC, goblinr commented
> "Вариант 1:Имеется возможность проверки, есть ли наземный маршрут между двумя контактами"
> Это значит полностью исключить варианты переправы на пароме и т.п?Я пока что просто задаю, в запросе mode = walking
Не надо ничего исключать. Просто строй маршрут, если маршрут построился, значит есть возможность добраться, если нет - то нет.

2020-06-07 09:37 UTC, goblinr commented
> И как хранить api ключи в проекте?

Не надо их в проекте хранить. Они не должны попадать в репозиторий.
GitGuardian тебе об этом и говорит. Тебе теперь нужно засквошить твои коммиты и исключить все ключи api. После этого сделать git push -f чтобы затереть историю. Тогда GitGuardian пропустит твой PR

2020-06-07 12:59 UTC, KalimullinIlnaz commented
мне кажется я что то тут неправильно сделал во время объедения коммитов и тд

2020-06-07 15:57 UTC, goblinr commented
> мне кажется я что то тут неправильно сделал во время объедения коммитов и тд

У тебя ветка судя по всему сильно отстает от мастера
<img width="413" alt="Снимок+экрана+2020-06-07+в+19 55 12" src="https://user-images.githubusercontent.com/2997073/83973660-09070700-a8f9-11ea-9f1d-ddadc428b1c1.png">
Или ты изменения из ДЗ с помощью cherry-pick добавлял в ветку `CourseWork`?

2020-06-07 16:02 UTC, KalimullinIlnaz commented
Я ещё не добавлял изменения из дз

2020-06-07 16:10 UTC, goblinr commented
> Я ещё не добавлял изменения из дз

Откуда тогда у тебя здесь https://github.com/KalimullinIlnaz/AndroidLessons/pull/10/files#diff-25cbb3a80f3f8cda92c6669b04a4fc2fR59

2020-06-07 16:12 UTC, KalimullinIlnaz commented
Я ещё до объяснения темы пробовал через rxjava делать

2020-06-07 16:13 UTC, goblinr commented
Тебе нужно либо сделать merge из `master` ветки в ветку курсовой. Либо сделать rebase ветки  `CourseWork` на `master`.  Иначе потом замучаешься конфликты разруливать.

2020-06-07 16:13 UTC, KalimullinIlnaz commented
Обновить тогда ветку до уровня мастера и снова запушить?

2020-06-07 16:14 UTC, KalimullinIlnaz commented
git pull origin master тогда прописать в моей ветке?

2020-06-07 16:16 UTC, KalimullinIlnaz commented
А или это через git fetch делается

2020-06-07 16:19 UTC, goblinr commented
> git pull origin master тогда прописать в моей ветке?

Если хочешь обновить ветку с помощью git merge, то:
git checkout CourseWork
git merge master
Затем разрулить конфликты и закоммитить мержевый коммит и пропушать

Если с помощью git rebase:
git checkout CourseWork
git rebase master
Затем разрулить конфликты и пропушать ветку с форсом.

2020-06-07 16:20 UTC, KalimullinIlnaz commented
Понял, спасибо

2020-06-08 05:26 UTC, goblinr requested changes

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +        getActivity().getMenuInflater().inflate(R.menu.map_item,menu);
Здесь что-то не то. Почему 2 раза `inflate`?

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +        return super.onOptionsItemSelected(item);
Здесь нужно проверять, что именно по действию с картой был тап пользователя, прежде чем открывать карту

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/FullMapFragment.java
> +    private String from, to,result;
Не объявляй поля так никогда. Это не читаемо.

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/FullMapFragment.java
> +        fullMapPresenter.showMarkers();
А нам точно не нужно дождаться `onMapReady` прежде чем просить презентер показать маркеры?

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/FullMapFragment.java
> +        map.setOnMapClickListener(latLng -> {
Задача была построить маршрут между существующими адресами контактов, а не между 2-х произвольных точек на карте. Ты должен отслеживать тап по маркерам, а не по карте.

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/FullMapFragment.java
> +        List<LatLng> mPoints = PolyUtil.decode(route);
Данное действие - ресурсозатратно. Нужно это сделать на `computation` scheduler'е в презентере

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +                .subscribe(list -> getViewState().showMarkers(list)));
Нужна обработка ошибки

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +        //Работу с retrofit, как я понял, можно через rxjava сделать?(
Да, нужно RxJava Call Adapter просто добавить

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +                });
Это все нужно вынести в репозиторий. Это нарушает принцип **S**

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +                point.longitude);
Это все нужно вынести в репозиторий.

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/FullMapView.java
> +    void showRoute(String route,String status);
Лучше прописать необходимые стратегии для методов. Это является правилом хорошего тона при использовании Moxy

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +        <Button
Сюда надо еще добавить адрес контакта, если он есть. Если нет, надпись: "Добавить адрес на карте"

2020-06-08 05:26 UTC, goblinr commented on MyApplication/app/src/main/res/menu/map_item.xml
> +        android:id="@+id/map"
У тебя уже есть одно меню, зачем тебе еще одно?

2020-06-08 09:49 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +        <Button
То есть добавить ещё одно поле к телефонному номеру, почте и тд, а кнопку сделать зависящую от того, добавлен ли адрес у контакта или нет. Если адрес есть то состояние "Посмотреть местоположение на карте", если нет, то "Добавить адрес на карте"
Или сделать текст на кнопке зависящий от адреса, то есть, если он есть, то отображается адрес, если нет, то "Добавить адрес на карте"

2020-06-08 10:14 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +        <Button
1-й вариант

2020-06-08 15:49 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +                });
Я, вроде как, преобразовал обычный ретрофит запрос в запрос через rx
![image](https://user-images.githubusercontent.com/63044917/84051390-c35d4380-a9b7-11ea-8321-c26e0c391828.png)
![image](https://user-images.githubusercontent.com/63044917/84051304-9c067680-a9b7-11ea-8ad5-f29740b4f79e.png)
но как мне получать и обрабатывать это в презентере(то есть, как достать нужное мне значение)?

2020-06-08 16:39 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +                });
Я не понял вопроса.  Тебе нужно скрыть работу с ретрофитом за репозиторием, наружу у тебя из репозитория для построения пути будет торчать только Single с набором точек для показа маршрута на карте.

2020-06-09 15:43 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +        compositeDisposable.add(geocodeRepository.getAddressFromYandexService(coordinate)
То что нужно делать на другом потоке я уже заметил

2020-06-10 05:10 UTC, goblinr requested changes

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactDetailsFragment.java
> +            btnLocationOnMap.setText("Посмотреть местоположение на карте");
Захардкоженные строки.

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/FullMapFragment.java
> +        Toast.makeText(getContext(),"Не существует наземного маршрута", Toast.LENGTH_SHORT).show();
Захардкоженная строка

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
> +    private String address;
Это не верно. `address` у тебя не задается ни в одном из конструкторов класса. Он не может быть в этом случае `@NonNull`, только `@Nullable`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
> +    public String getAddress() {
Адрес у тебя по факту `@Nullable` а не `@NonNull`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
> +    public void setAddress(String address) {
`nullability` аннотацию к параметру

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Возможен `IndexOutOfBoundsException`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/FullMapPresenter.java
> +            .observeOn(AndroidSchedulers.mainThread())
Получать данные нужно на io а вот конвертировать их уже на  computation, правильно будет так:
```java
compositeDisposable
            .add(geocodeRepository.getRoutePointsFromGoogleService(from, to)
            .subscribeOn(Schedulers.io())
            .observeOn(Schedulers.computation())
            .map(this::getPoints)
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(...)
```

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +    public Contact getData(String id){
`private`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +                    return dto;
Т.к. тебе эта `dto` не нужна в `subscribe` - оператор `map` здесь не нужен. Достаточно будет воспользоваться оператором `doOnSuccess`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +                .getGeoObjectCollection().getFeatureMember().get(0).getGeoObject()
Возможен `IndexOutOfBoundsException`

2020-06-10 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/FullMapView.java
> +    void showMessageNoRoute();
Ты уверен, что при каждом повороте экрана - нужно показывать это сообщение?

2020-06-10 05:12 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/FullMapView.java
> +    void showMessageNoRoute();
Почитай по-внимательнее про стратегии в Moxy

2020-06-10 12:17 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/FullMapView.java
> +    void showMessageNoRoute();
OneExecutionStateStrategy  тогда использовать?

2020-06-10 12:21 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/FullMapView.java
> +    void showMessageNoRoute();
Да

2020-06-10 12:27 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Тогда в этом же методе установить проверку routes.isEmpty или что делать?

2020-06-10 12:28 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Подумай.

2020-06-10 15:06 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Обернуть в трай кэтч, если  IndexOutOfBoundsException, то говорить, что запрос на сервер прошел неудачно?

2020-06-10 16:36 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Зачем? Запрос же на самом деле прошел удачно, раз мы дошли до этого момента.

2020-06-10 17:04 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
Тогда, выводить, что маршрут отсутствует?)

2020-06-10 19:00 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/GoogleRouteResponseDTO.java
> +        return this.routes.get(0).overview_polyline.points;
yep

2020-06-10 19:12 UTC, KalimullinIlnaz commented
Мне кажется как то неправильно возвращать "", может там стоит константу использовать какую то с понятным названием?

2020-06-10 19:24 UTC, goblinr requested changes

2020-06-10 19:24 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
>      public void setLongitude(double longitude){
Зачем здесь `@Nullable`? `void` не нуждается в `nullability` аннотации.

2020-06-10 19:24 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/models/Contact.java
> +    public void setAddress(String address) {
Не исправлено.

2020-06-10 19:24 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/MapPresenter.java
> +                .doOnSuccess( (dto) ->
неверно, `observeOn(AndroidSchedulers.mainThread())` должен идти после `doOnSuccess`, сейчас получается, что запись в БД осуществляется на главном потоке программы - что неприемлемо.

2020-06-10 19:36 UTC, goblinr approved these changes
Можно мержить в `master`. Все последующие ДЗ будешь делать уже на готовом функционале курсовой. В итоге, к концу курса у тебя будет полностью готовая курсовая и сданы все ДЗ

2020-06-10 19:38 UTC, merged