Dagger2
KalimullinIlnaz/AndroidLessons pull request #14
Opened 2020-06-13 16:59 UTC by KalimullinIlnaz

Рефакторинг приложения  с использованием DI

2020-06-13 17:14 UTC, KalimullinIlnaz commented
Как я понимаю, нужно ещё сделать модули для data base и retrofit, но как их инжектить в репозиторий пока не понятно

2020-06-15 05:10 UTC, goblinr requested changes

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/build.gradle
> +    annotationProcessor 'com.google.dagger:dagger-android-processor:2.20'
`api` -> `implementation`

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/app/AppDelegate.java
> +        appComponent.inject(this);
Какой смысл в этом `inject`, если у тебя в классе `AppDelegate` нет ни одной аннотации `@Inject`?
Если ты не планируешь здесь инъекций - то можно удалить этот `inject`

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/di/app/AppComponent.java
> +    void inject(AppDelegate appDelegate);
как писал выше - этот `inject` избыточен, т.к. `AppDelegate` не требует инъекций

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/di/app/AppModule.java
> +        return application.getBaseContext();
здесь нужно просто `return application;`

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/di/map/MapModule.java
> +        return new ContactDetailsRepository(context);
`ContactDetailsRepository` требуется аж в 3-х модулях. Как думаешь, может быть лучше вынести его в `@Singleton` скоуп?

2020-06-15 05:10 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/DataBaseRepository.java
>                  AppDatabase.class,"user_location").build();
У тебя уже есть `DataBaseModule` в котором провайдится `AppDatabase`. Тебе нужно использовать инстанс `AppDatabase` предоставляемый даггером.

2020-06-15 13:09 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/DataBaseRepository.java
>                  AppDatabase.class,"user_location").build();
То есть я ставлю аннотацию inject над полем database и в конструкторе DataBaseRepository
инжекчу database component?

2020-06-15 15:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/DataBaseRepository.java
>                  AppDatabase.class,"user_location").build();
```java
@Inject
public DataBaseRepository(Context context, 
                                               ContactDetailsRepository contactDetailsRepository,
                                               AppDatabase database) {
...
}
```

2020-06-15 16:18 UTC, goblinr approved these changes

2020-06-15 16:29 UTC, merged