CleanArchitecture
KalimullinIlnaz/AndroidLessons pull request #15
Opened 2020-06-19 15:55 UTC by KalimullinIlnaz

Рефакторинг кода с использованием Чистой архитектуры

2020-06-20 10:34 UTC, goblinr requested changes
1. Все детали реализации, относящиеся к андроиду и библиотекам - не должны быть в модуле чистой бизнес-логики. Еще раз пересмотри лекцию.
2. в `app` модуле должен остаться только DI.  Никаких фрагментов, активностей, презенторов и пр. все это должно уйти в модуль - андоид-библиотеку

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Этого не должно быть в entity модуле

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/build.gradle
> +    annotationProcessor "androidx.room:room-compiler:2.2.5"
Этого тоже не должно быть здесь

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/Contact.java
> +package Entities;
Название пакета - не соответствует java конвенции

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/FeatureMember.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/GeoObject.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/GeoObjectCollection.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/GeocoderMetaData.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/GeocoderResponseMetaData.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/GoogleRouteResponseDTO.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/Location.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/MetaDataProperty.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/MetaDataProperty_.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/Point.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/Response.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Entities/YandexAddressResponseDTO.java
> +package Entities;
Этого класса не должно быть в entity модуле - он относится к деталям реализации

2020-06-20 10:34 UTC, goblinr commented on MyApplication/java/src/main/java/Interactors/db/DataBaseInteractor.java
> +public interface DataBaseInteractor {
Само название этого интерфейса "кричит" о том что ты что-то делаешь не так

2020-06-20 10:36 UTC, goblinr commented
Вобщем, все неверно, все не так. Нужно все переделать

2020-06-20 10:55 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
"в app модуле должен остаться только DI. Никаких фрагментов, активностей, презенторов и пр. все это должно уйти в модуль - андоид-библиотеку" я сделал так, только когда проект собирался получилась круговая зависимость, как тогда это решать?

2020-06-20 11:00 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Тебе нужно подумать, как переделать твою структуру конфигурации DI - что бы можно было так сделать. Сначала попробуй сам подумать. Если сдашься, я тебе подскажу.

2020-06-20 15:23 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Модули, компоненты, скоупы связанные с фрагментами и тп будут в андроид библиотеке так?)

2020-06-20 15:24 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
А модуль андроид приложения останется android.application?

2020-06-20 15:30 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
>Модули, компоненты, скоупы связанные с фрагментами и тп будут в андроид библиотеке так?)
А модуль андроид приложения останется android.application?

Зачем? Фрагментам и пр. сущностям нужны зависимости, пусть они задекларируют интерфейс, через который будут получать необходимые зависимости, а в `app` модуле будут реализации этих интерфейсов в виде даггеровских компонентов. Улавливаешь мысль?

2020-06-20 18:47 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
То есть, для каждого фрагмента, презентора, репозитория, модели... каждого класса, который мне нужен в library, я создаю интерфейс, который будет использоваться в app модуле, то есть нужный компонент будет имплементировать нужный интерфейс и вот как куда дальше... 
Я не могу понять как это написать.

2020-06-20 19:29 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
ну вот смотри, у тебя есть AppDelegate, который единственный, кто должен остаться в `app` модуле. 
Единственное что он должен - предостовлять другим компонентам  
контейнеры, через которые они смогут получить зависимости. Давай опишем интерфейс для такого контейнера и положем его в библиотеку:

```java
public interface AppContainer {
    ContactsListContainer plusContactsListContainer();
    /*остальные контейнеры*/
}

public interface ContactsListContainer {
	void inject(ContactListFragment contactListFragment);
}
```

так же в модуле библиотеки, нам понадобится интерфейс для получения этого контейнера:
```java
public interface HasAppContainer {
	@NonNull
	AppContainer appContainer();
}
```

В модуле библиотеке, в фрагменте:
```java
public class ContactListFragment extends MvpAppCompatFragment implements ContactListView, ContactAdapter.onContactListener {

	@Override
    public void onAttach(@NonNull Context context) {
        Application app = requireActivity().getApplication();
        if (!(app instanceof HasAppContainer)) {
        	throw new IllegalStateException();
        }
        ContactsListContainer contactsListComponent = ((HasAppContainer)app).appContainer()
                .plusContactsListContainer();
        contactsListComponent.inject(this);

        super.onAttach(context);
    }
}
```

теперь напишем реализацию на Dagger2 в `app` модуле:
```java
@Singleton
@Component(modules = {/*модули*/})
public interface AppComponent extends AppContainer {
	ContactsListComponent plusContactsListContainer();
	/*остальные контейнеры*/
}
```

AppDelegate:
```java
public class AppDelegate extends Application implements HasAppContainer {

    @Nullable
    private AppComponent appComponent;


    @Override
    public void onCreate() {
        super.onCreate();
        initDependencies();
    }

    private void initDependencies() {
        appComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this))
                .build();
    }

    @NonNull
    @Override
    public AppContainer appContainer(){
        if (appComponent == null){
            initDependencies();
        }
        return appComponent;
    }
}
```

ContactsListComponent:
```java
@ContactsListScope
@Subcomponent(modules = {ContactsListModule.class})
public interface ContactsListComponent extends ContactsListContainer {
}
```

2020-06-20 21:46 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
Спасибо, вроде как поправил

2020-06-21 11:02 UTC, goblinr requested changes

2020-06-21 11:02 UTC, goblinr commented on MyApplication/application/src/main/AndroidManifest.xml
> +    /
Синтаксическая ошибка

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/entities/Contact.java
> +package entities;
По-прежнему не соответствует java конвенции, должно быть что-то такое : `com.a65apps.kalimullinilnazrafilovich.entities `

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/entities/Contact.java
> -    @NonNull
Используй аннотации из стандарта jsr250

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation fileTree(dir: 'libs', include: ['*.jar'])
А где rx? Как ты собрался работать с асинхронным кодом?

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/interactors/contacts/ContactListInteractor.java
> +    ArrayList<Contact> loadContactsOnRequest(String query);
`Single<List<Contact>> loadContactsOnRequest(String query);`

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/interactors/contacts/ContactListRepository.java
> +    ArrayList<Contact> getContactsOnRequest(String query);
`Single`

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/interactors/details/ContactDetailsInteractor.java
> +    Contact loadDetailsContact(String id);
`Single`

2020-06-21 11:02 UTC, goblinr commented on MyApplication/java/src/main/java/interactors/details/ContactDetailsRepository.java
> +    Contact getDetailContact(String id);
`Single`

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/AndroidManifest.xml
> +        android:name="com.a65apps.kalimullinilnazrafilovich.application.AppDelegate">
это нужно перенести в манифест `application` модуля. Manifest merging затем сделает свою работу по объединению манифестов. Если интересно, как он работает, можешь почитать здесь https://developer.android.com/studio/build/manifest-merge

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/app/AppModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.app;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/app/DataBaseModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.app;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/app/RepositoryModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.app;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/contactDetails/ContactDetailsModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.contactDetails;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/contacts/ContactsListModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.contacts;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/map/MapModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.map;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/routeMap/MapRouteModule.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.routeMap;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/scope/ContactDetailsScope.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.scope;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/scope/ContactsListScope.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.scope;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/scope/MapRouteScope.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.scope;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/di/scope/MapScope.java
> +package com.a65apps.kalimullinilnazrafilovich.library.applicaiton.di.scope;
Этот класс должен быть в `application` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenter.java
> +    private final DataBaseRepository dataBaseRepository;
У презентера не должно быть связи с репозиторием. Только с интерактором.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenter.java
> +    private final DataBaseRepository dataBaseRepository;
Интерактор при этом должен находиться в твоем `java` модуле

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +        return dataBaseRepository.getContactById(id);
У презентера не должно быть связи с репозиторием. Только с интерактором.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +        compositeDisposable.add(geocodeRepository.getAddress(coordinate)
У презентера не должно быть связи с репозиторием. Только с интерактором.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapRoutePresenter.java
> +    private final GeocodeRepository geocodeRepository;
У презентера не должно быть связи с репозиторием. Только с интерактором.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactDetailsRepositoryImpl.java
> +public class ContactDetailsRepositoryImpl implements ContactDetailsRepository {
Это очень дурная практика - называть реализации с постфиксом `Impl`. Назови полезным именем, например, `ContactDetailsContentResolverRepository`, т.к. в данном случае, этот репозиторий работает с единственным источником данных - `ContentResolver`

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactListRepositoryImpl.java
> +public class ContactListRepositoryImpl implements ContactListRepository {
Нормальное название реализации

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/DataBaseRepository.java
> +public interface DataBaseRepository {
Этот класс должен находиться в `java` модуле и он должен называться `LocationRepository`. Т.к.сущность, с которой он работает  - называется `Location`.

Так же, обрати внимание, что помимо того что он работает с `Location`, он еще предоставляет `Contact` - что является явным нарушением принципа единственной ответственности и сегрегации интерфейсов.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/DataBaseRepositoryImpl.java
> +public class DataBaseRepositoryImpl implements DataBaseRepository {
Название класса

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepository.java
> +    Single<GoogleRouteResponseDTO> getRoutePoints(String from, String to);
Репозиторий должен возвращать сущности бизнес-слоя приложения. Пересмотри лекцию еще раз и обрати внимание на мэпперы данных.

2020-06-21 11:02 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Название класса

2020-06-21 18:16 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Можно объяснить мне про сущности, а то я уже мягко говоря запутался в своем проекте.
У меня на данный момент сущность контактов, также должна быть сущность описывающая местоположение контактов, также у меня есть маршрут между контактами это тоже должно стать сущность типо route(или что то подобное)?
Сущности у вас в лекции написаны как интерфейсы, то есть в java модуле будут только интерфейсы с методами типо name,email и тд. а в library модуле уже их реализации.
(Также могу загрузить проект, который написал на данный момент, но там присутствует масса ошибок)

2020-06-21 18:33 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Все верно. Сущности - это бизнес-модели твоего приложения. Как ты верно заметил, в данном приложении можно выделить 3 сущности - `Контакт`, `Локация`, связь между `Контактом` и `Локацией` - 1 к 1, и `Маршрут`. У `Маршрута` связь с `Локацией`

По поводу сущностей как интерфейсов - не обязательно делать их интерфейсами и тем более не должно быть каких-то реализаций этих сущностей в более низких слоях. Желательно держать эти сущности иммутабельными.  Главная суть сущностей - они должны быть "чистыми", никаких зависимостей от библиотек, никаких специфичных аннотаций от каких-либо фрэймворков, вроде Room, Gson и пр. Т.е. это должны быть чистые бизнес-модели. И твоя бизнес-логика(Интеракторы) должны оперировать этими чистыми бизнес-моделями.

Репозитории же - это та граница, где данные из низких слоев преобразуются в удобный формат для твоей бизнес-логики, т.е. из ORM в модель и обратно, из JSON в модель и обратно и т.д.

2020-06-21 18:44 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Тогда сущность контакт остается такой же.
Сущность маршрут будет иметь в себе набор точек в виде стринга и все?
А сущность локация... она же у меня orm как мне ее представить в java модуле? Окей, я описываю все поля и методы, а как куда дальше, как создавать сущность orm в library, на данном моменте я остановился

2020-06-21 18:48 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
1. Ты уверен, что твоей бизнес-логике будет удобна сущность `Маршрута` у которой набор точек будет в виде строки? Я сильно сомневаюсь в этом.
2. Не думай об ORM думай сначала о бизнес-задаче, ORM - вторична. Каким образом твоя бизнес-сущность будет попадать в БД - это уже 10-е дело.

2020-06-21 18:54 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
1. тогда набор точек в виде листа LatLng, хотя возможно стоит в нем хранить начальную и конечную точку.

2020-06-21 18:57 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
2.То есть сущность локация будет иметь в себе координаты, адрес и id контакта у которого эта локация, так же?

2020-06-21 19:20 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Если бы я нормализовал сущности и связи между ними, у меня скорее всего получилось бы что-то такое:
`Contact` связь с `Location` 1 к 1 и данные контакта
`Location` - связь с `Point` 1 к 1 и адрес, связь с `Contact` 1 к 1
`Route` связь с `Location` 1 ко многим (возможно в будущем можно будет проложить маршрут через 3 и более точек), связь с `Point` 1 ко многим
`Point` - координата на карте latitude, longitude

При такой структуре связей, я бы мог решить большую часть бизнес-задач, которые мне с ходу приходят в голову.

2020-06-21 19:25 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
На самом деле, у `Contact` еще должна быть связь с `Email` 1 ко многим  и с `Phone` 1 ко многим

2020-06-21 19:29 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
То есть 4 класса:
Point с полями latitude, longitude
Contact с  полями, которые были + поле Location
Location адрес, contact и point
Route list location и list point-ов
Так?)

2020-06-21 19:31 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Ты ждешь от меня одобрения? Я сказал как бы получилось, скорее всего, у меня(я думал над этой задачей всего 5 минут, пока писал этот текст). Возможно у тебя, получится по-другому.

2020-06-21 19:32 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/GeocodeRepositoryImpl.java
> +public class GeocodeRepositoryImpl implements GeocodeRepository {
Попробуй так тогда

2020-06-22 10:48 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/entities/Contact.java
> -    @NonNull
@PostConstruct??

2020-06-22 10:50 UTC, goblinr commented on MyApplication/java/src/main/java/entities/Contact.java
> -    @NonNull
`@NotNull`, есть еще `@Nonnull`  зависит от библиотеки, которую ты выберешь.

2020-06-22 10:55 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/entities/Contact.java
> -    @NonNull
А вот вопрос, так как в java модуле есть rxjava, то в нем тоже есть аннотация nonnull, это что то другое?

2020-06-22 10:58 UTC, goblinr commented on MyApplication/java/src/main/java/entities/Contact.java
> -    @NonNull
Тоже самое. Они все - одно и тоже

2020-06-22 16:22 UTC, goblinr requested changes

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/RepositoryModule.java
> +    public ContactDetailsContentResolverRepository provideContactDetailsContentResolverRepository(Context context) {
Наружу из модуля должен торчать интерфейс, а не конкретная реализация. Это нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/RepositoryModule.java
> +    public ContactLocationRepository provideContactLocationRepository(AppDatabase database,
нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/RepositoryModule.java
> +    public ContactDataBaseLocationRepository provideContactDataBaseLocationRepository(AppDatabase database){
нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/RepositoryModule.java
> +    public ContactListContentResolverRepository provideContactListContentResolverRepository(Context context){
нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/RepositoryModule.java
> +    public GeocodeRouteRepository provideGeocodeRouteRepository(Context context){
нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/contactDetails/ContactDetailsModule.java
> +    public ContactDetailsModel provideContactDetailsModel(ContactDetailsContentResolverRepository contactDetailsRepository,
нарушение принципа инверсии зависимости. наружу должен торчать интерфейс

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/contacts/ContactsListModule.java
> +    public ContactListModel provideContactListModel(ContactListContentResolverRepository contactListRepository){
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/contactDetails/ContactDetailsModule.java
> +        return new ContactDetailsPresenter(contactDetailsModel);
`ContactDetailsPresenter` должен зависеть от абстракции, нарушение принципа инверсии зависимости

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/contacts/ContactsListModule.java
> +        return new ContactListPresenter(contactListModel);
`ContactListPresenter ` должен зависеть от абстракции, нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/map/MapModule.java
> +        return new MapPresenter(contactLocationModel, contactDetailsModel);
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/map/MapModule.java
> +    public ContactLocationModel provideContactLocationModel(ContactLocationRepository contactLocationRepository){
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/map/MapModule.java
> +    public ContactDetailsModel  provideContactDetailsModel(ContactDetailsContentResolverRepository contactDetailsContentResolverRepository,
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/routeMap/MapRouteModule.java
> +        return new MapRoutePresenter(contactLocationModel, routeModel);
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/routeMap/MapRouteModule.java
> +    public ContactLocationModel provideContactLocationModel(ContactLocationRepository contactLocationRepository){
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/routeMap/MapRouteModule.java
> +    public RouteModel provideRouteModel(GeocodeRouteRepository geocodeRouteRepository){
нарушение принципа инверсии зависимостей

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Contact.java
> +    private Location location;
`final`.

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Contact.java
> +    public void setLocation(@Nullable Location location) {
сеттер удалить.

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Location.java
> +public class Location {
`final` ко всем полям
и nullability аннотации

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Point.java
> +public class Point {
`final` ко всем полям и nullability аннотации

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Route.java
> +public class Route {
`final` ко всем полям и nullability аннотации

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/details/ContactDataBaseRepository.java
> +public interface ContactDataBaseRepository {
Этот интерфейс избыточен. У тебя уже есть `ContactDetailsRepository` - его одного достаточно.
Тебе нужно просто написать 2 реализации этого интерфейса - одна будет работать с поставщиком контактов, другая с БД

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/details/ContactDataBaseRepository.java
> +    Single<Contact> getContactLocation(Single<Contact> contactEntitySingle);
`Singlе` как параметр, зачем?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/location/ContactLocationInteractor.java
> +    Single<Location> loadContactLocation(Contact contact, double latitude, double longitude);
Зачем тебе понадобились `latitude`, `longitude` в параметрах здесь?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/location/LocationRepository.java
> +    Single<Location> getContactLocation(Contact contact, double latitude, double longitude);
опять же не понятно, зачем координаты в этом методе?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/route/GeocodeRepository.java
> +    Single<Route> getRoute(String from, String to);
почему параметры - строки?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/route/RouteInteractor.java
> +    Single<Route> loadRoute(String from, String to);
почему параметры - строки?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/models/LocationORM.java
> +public class LocationORM {
`LocationORM` -> `LocationOrm`

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/models/LocationORM.java
> +    public LocationORM(){
зачем конструктор без параметров?

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                        contactLocationInteractor.loadContactLocation(contact, point.longitude, point.latitude)
1. Кажется я понял зачем координаты в параметрах. Название метода интерфейса - сбивает с толку, нужно переименовать метод
2. subscribe внутри subscribe - неприемлемо. Используй оператор `flatMap`

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapRoutePresenter.java
> +                    routeInteractor.loadRoute(from, to)
В моем понимании, на вход метода `loadRoute` должны подаваться 2 параметра типа `Point`

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapRoutePresenter.java
> +                    .map( (route) -> getListLatLnt(route))
опечатка в названии метода

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapRoutePresenter.java
> +    }
Всю эту логику нужно вынести в интерактор `RouteInteractor`

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactDataBaseLocationRepository.java
> +public class ContactDataBaseLocationRepository implements ContactDataBaseRepository {
Как я уже писал выше - этот класс не нужен.

2020-06-22 16:22 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactLocationRepository.java
> +                .subscribe(
`subscribe` внутри rx цепочки - неприемлемо. Используй оператор `flatMap`
```java
Single.fromCallable( () -> database.locationDao().getAll())
  .flatMapObservable(list -> Observable.fromIterable(list))
  .flatMapSingle(item -> contactDetailsContentResolverRepository.getDetailsContact(item.getContactID()).map(contact -> new Pair<LocationORM, Contact>(item, contact)))
  .map(pair -> new Location(...))
  .toList()
```

2020-06-22 20:24 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/details/ContactDataBaseRepository.java
> +public interface ContactDataBaseRepository {
То есть два репозитория реализуют этот один интерфейс, в котором будет два метода для получения контактов и контакта с локацией?

2020-06-23 05:50 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/details/ContactDataBaseRepository.java
> +public interface ContactDataBaseRepository {
Я думаю можно обойтись вообще одной реализацией.  Просто эта реализация будет работать и с поставщиком контактов и с БД

2020-06-23 18:05 UTC, goblinr requested changes

2020-06-23 18:05 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Point.java
> +    public Point(@Nullable double latitude, @Nullable double longitude) {
Примитивы не могут быть  `null`

2020-06-23 18:05 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/Route.java
>      public List<Point> getPoints() {
`@Nullable`

2020-06-23 18:05 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/location/ContactLocationInteractor.java
> +    Single<Location> loadContactLocationByCoordinate(Contact contact, double latitude, double longitude);
Здесь подойдет больше `createOrUpdateContactLocationByCoordinate`

2020-06-23 18:05 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/location/LocationRepository.java
> +    Single<Location> getContactLocationByCoordinate(Contact contact, double latitude, double longitude);
Здесь так же, мы либо создаем новый `Location`, либо  обновляем уже существующий

2020-06-23 18:05 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Я думаю эти 2 действия можно объединить в одно

2020-06-23 18:05 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +        contactDetailsInteractor.loadDetailsContact(id)
Не следишь за подпиской

2020-06-23 18:40 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Cохранять сразу в репозитории?

2020-06-23 18:41 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Да

2020-06-23 18:45 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
нашел такой метод blockingGet(), он тут приемлем?

2020-06-23 18:46 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Нет, конечно. Зачем он тебе?

2020-06-23 18:48 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Заметил, что через него можно просто получить объект Location из single<Location>

2020-06-23 18:49 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/MapPresenter.java
> +                    .doOnSuccess((dto) -> contactLocationInteractor.saveContactLocation(dto, contact)))
Да, можешь, но это заблокирует тот поток, на котором ты вызовешь этот метод

2020-06-23 19:32 UTC, goblinr requested changes

2020-06-23 19:32 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactLocationRepository.java
> +        return locationSingle;
Так делать нельзя. `subscribe` должен быть исключительно только в презентере и нигде больше.

2020-06-24 04:13 UTC, goblinr requested changes

2020-06-24 04:13 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/ContactLocationRepository.java
> +                .subscribeOn(Schedulers.io())
`subscribeOn` уже есть в презентере, вместе с этим - у тебя получается уже 2 `subscribeOn` в rx цепочке. Так делать нельзя, это плохо влияет на производительность. Нужно оставить только 1 `subscribeOn` либо здесь, либо в презентере.

2020-06-24 09:49 UTC, goblinr approved these changes

2020-06-24 09:54 UTC, merged