Тесты для приложения
KalimullinIlnaz/AndroidLessons pull request #16
Opened 2020-06-25 15:15 UTC by KalimullinIlnaz

2020-06-25 17:25 UTC, KalimullinIlnaz commented
Получается нужно создать сервис и в него вынести создание и установку уведомления о дне рождения?

2020-06-25 19:34 UTC, goblinr commented
> Получается нужно создать сервис и в него вынести создание и установку уведомления о дне рождения?

```java
// entity
class BirthdayNotification {...}

// Interactor
interface NotificationInteractor {...}

// Repository
interface NotificationRepository {...}
```
И детали реализации

Вся бизнес-логика по напоминанию будет инкапсулирована в деталях реализации `NotificationInteractor`  
детали реализации `NotificationRepository` будут инкапсулировать логику по работе с  `AlarmManager` и `NotificationManager`

2020-06-26 11:47 UTC, goblinr requested changes

2020-06-26 11:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/BirthdayNotification.java
> +    public boolean isStatus() {
Название метода не говорящее

2020-06-26 11:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/BirthdayNotification.java
> +    private final boolean status;
Название поля - не понятное. Не ясно - что за статус такой?

2020-06-26 11:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
А где бизнес-логика?
Где все кейсы, которые описаны в задании?

2020-06-26 11:47 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/fragments/ContactDetailsFragment.java
>                  PendingIntent.FLAG_NO_CREATE) != null){
Этого не должно быть здесь. Проверка статуса напоминания, должна происходить в репозитории.
Здесь же ты просто должен отобразить статус кнопки.

2020-06-26 11:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationInteractor.java
> +    void setOrRemoveBirthdayNotification(BirthdayNotification birthdayNotification);
на вход подавать уже готовую модель `BirthdayNotification` не нужно. Достаточно передать `Contact`.
на выходе же ты должен получить актуальное состояние оповещения для контакта.
```java
public interface NotificationInteractor {
    BirthdayNotification setOrRemoveBirthdayNotification(Contact contact);
}
```

2020-06-26 11:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationRepository.java
> +    void onOrOffBirthdayReminder(BirthdayNotification birthdayNotification);
О том, включать или выключать оповещение - должен решать не репозиторий, а интерактор.

2020-06-26 11:47 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/fragments/ContactDetailsFragment.java
> +        contactDetailsPresenter.setOrRemoveNotification(birthdayNotification);
Как уже писал выше. `BirthdayNotification` не должна создаваться здесь. Это ответственность репозитория.

2020-06-26 11:47 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +        alarmManager.set(AlarmManager.RTC, birthOfDay.getTimeInMillis(), alarmPendingIntent);
Логику по переустановке оповещения, следует пере-использовать здесь. Иначе получается дублирование кода.

2020-06-26 11:47 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/NotificationAlarmManagerRepository.java
> +    public void onOrOffBirthdayReminder(BirthdayNotification birthdayNotification) {
Всю бизнес-логику из этого метода следует вынести в интерактор. Именно там она должна быть.

2020-06-26 14:48 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
добавление, удаление, добавление напоминания для контакта родившегося 29 февраля и добавление напоминания для контакта родившегося 29 февраля в високосный год всех их отдельными методами описать?

2020-06-26 14:55 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
Публичный метод должен быть 1. А вот приватных - можешь делать на каждый кейс, если нужно.

2020-06-26 15:16 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
Так, получается в интеракторе также один метод, а в моделе будут присутствовать методы для описанных в задании кейсов и они уже будут нужные методы из репозитория?

2020-06-26 15:18 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
Я выше так и написал.

2020-06-26 20:44 UTC, KalimullinIlnaz commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
Здесь же в метод ещё стоит ввести такой параметр как время, то как вы в в лекции рассказывали, чтобы было удобно тестировать?

2020-06-29 04:01 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        notificationRepository.onOrOffBirthdayReminder(birthdayNotification);
Верно, не обязательно как параметр в метод. Это может быть просто - зависимость класса

2020-06-29 12:11 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +        alarmManager.set(AlarmManager.RTC, birthOfDay.getTimeInMillis(), alarmPendingIntent);
Не понял, что нужно сделать

2020-06-29 12:12 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +        alarmManager.set(AlarmManager.RTC, birthOfDay.getTimeInMillis(), alarmPendingIntent);
Вызывать метод репозитория?

2020-06-29 12:43 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +        alarmManager.set(AlarmManager.RTC, birthOfDay.getTimeInMillis(), alarmPendingIntent);
Вся эта логика у тебя уже есть в реализации интерактора. Нужно ее пере-использовать здесь.

2020-06-29 15:53 UTC, goblinr requested changes

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/fragments/ContactDetailsFragment.java
>          }
`toggleButton.setChecked(birthdayNotification.getNotificationWorkStatusBoolean());`

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +    BroadReceiver(NotificationInteractor notificationInteractor){
Так делать нельзя. У BroadcastReceiver должен быть конструктор по умолчанию и никаких "своих" конструкторов. Мы не властны над его созданием, за нас его создает ОС.

Используй инъекцию в поля для этого класса, что бы предоставить зависимости

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
>      private void repeatAlarm(Context context,String id,String text) {
Здесь нужно пере-использовать логику `NotificationInteractor`

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/NotificationAlarmManagerRepository.java
> +        return new BirthdayNotification(contact, true);
Вся эта логика должна быть в чисто-java библиотеке в реализации интерактора, а не в репозитории. Репозиторий не должен производить какую-либо бизнес-логику, он только складывает и отдает данные, ВСЕ.

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/repositories/NotificationAlarmManagerRepository.java
> +        return new BirthdayNotification(contact, true);
Это касается всех остальных методов в этом классе так же

2020-06-29 15:53 UTC, goblinr commented on MyApplication/library/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/ExampleUnitTest.java
> +        assertEquals(5, 2 + 2);
???

2020-06-30 14:09 UTC, KalimullinIlnaz commented on MyApplication/library/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/ExampleUnitTest.java
> +        assertEquals(5, 2 + 2);
Это правильная код теста или что то стоит поправить?
![image](https://user-images.githubusercontent.com/63044917/86136160-648d7480-baf4-11ea-80c7-8afc20fe578a.png)

2020-06-30 18:57 UTC, goblinr requested changes

2020-06-30 18:57 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +        GregorianCalendar gregorianCalendar = (GregorianCalendar) GregorianCalendar.getInstance(TimeZone.getDefault(), Locale.getDefault());
Локали и таймзоны - это неявные входы в твою функцию, их следует скрывать за абстракцией.

2020-06-30 18:57 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +                );
1. не следишь за подпиской
2. пересмотри лекцию про BroadcastReciever, как только заканчивается работа метода `onReceive` - система помечает этот компонент на удаление, поэтому если ты делаешь асинхронную работу в нем, необходимо воспользоваться методом `goAsync()` на **главном** потоке и не забыть вызвать `finish` на **главном** потоке программы

2020-06-30 20:42 UTC, KalimullinIlnaz commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +                );
![image](https://user-images.githubusercontent.com/63044917/86174987-47c06380-bb2b-11ea-9f5b-e22d1a7fb05f.png)
а где отписываться?

2020-07-01 11:01 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +                );
В принципе, с Single'ом в данном случае можно опустить подписку.

2020-07-01 11:18 UTC, goblinr requested changes

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +package com.a65apps.kalimullinilnazrafilovich.library;
Почему этот тест находится в модуле `library` а не в `java`? Это неверно. Модульные тесты должны находиться в тех же самых модулях, классы которых они тестируют

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +import android.content.Context;
Никаких импортов связанных с андроидом здесь не должно быть

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +    private AlarmManager alarmManager;
Это не нужно здесь.

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +    private Context context;
Это тоже не нужно здесь

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +    private PendingIntent alarmPendingIntent;
Это не нужно в этом тесте

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +        alarmManager = Mockito.spy(AlarmManager.class);
AlarmManager тебе не нужен в этих тестах

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +        NotificationRepository notificationRepository = new NotificationAlarmManagerRepository(context);
Тебе нужна не конкретная реализация `NotificationRepository` а мок. Ты же тестируешь логику `NotificationModel` и тебе не важна логика внутри `NotificationRepository`. Поэтому его нужно замокать.

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationRepositoryUnitTest.java
> +public class NotificationRepositoryUnitTest {
А репозиторий тебе зачем тестировать?

2020-07-01 11:18 UTC, goblinr commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationRepositoryUnitTest.java
> +public class NotificationRepositoryUnitTest {
Мы специально выносим всю логику в интеракторы, что бы протестировать бизнес-логику в простых junit тестах без подключения тяжеловесных UI тестов

2020-07-01 11:18 UTC, goblinr commented on MyApplication/library/build.gradle
> +        unitTests.includeAndroidResources = true
Это тебе не нужно

2020-07-01 13:24 UTC, KalimullinIlnaz commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +        NotificationRepository notificationRepository = new NotificationAlarmManagerRepository(context);
Здесь я установливаю дату, но уставляется не сама дата, а поля(как я понял с помощью дебага), как мне установить дата, что в дальнейшем получать из нее миллисекунды?
![image](https://user-images.githubusercontent.com/63044917/86248790-070e2c00-bbb7-11ea-9306-0c32a4157b5c.png)

2020-07-01 13:43 UTC, KalimullinIlnaz commented on MyApplication/application/src/test/java/com/a65apps/kalimullinilnazrafilovich/library/NotificationModelTest.java
> +        NotificationRepository notificationRepository = new NotificationAlarmManagerRepository(context);
А вроде разобрался, нужно получать сначала объекта Data, а после из него время

2020-07-01 14:47 UTC, goblinr requested changes

2020-07-01 14:47 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'junit:junit:4.12'
`junit` не должен попадать в production код. Нужно удалить эту зависимость.

2020-07-01 14:47 UTC, goblinr commented on MyApplication/java/build.gradle
> +    implementation 'org.mockito:mockito-core:2.28.2'
`testImplementation`

2020-07-01 14:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/tests/NotificationModelTest.java
> +        MockitoAnnotations.initMocks(this);
Это лишнее, ты уже запускаешь тесты с `@RunWith(MockitoJUnitRunner.class)`

2020-07-01 14:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/tests/NotificationModelTest.java
> +    public void onBirthdayNotification_Should_Return_BirthdayNotification() {
Название теста очень расплывчатое и не конкретное

2020-07-01 14:47 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/tests/NotificationModelTest.java
> +    public void onBirthdayNotification_Should_Return_BirthdayNotification() {
В целом тест теперь корректный.
Теперь осталось проверить все остальные кейсы из ДЗ.

Так же советую группировать блоки кода в тесте по смыслу:
```java
// Дано
/*создаем необходимые условия для теста*/

// Когда
/*Вызываем действие*/

// Тогда
/*Проверяем результат*/
```

2020-07-01 14:47 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/receivers/BroadReceiver.java
> +                });
Это не верно. Абсолютно. Судя по всему,  Rx ты очень плохо понял.
1. из **любого** оператора `null` возвращать нельзя, Rx обязательно выкинет исключение в этом случае.
2. оператор `flatMap` здесь в принципе не нужен
3. холодный `Single` не начнет выполнение своей цепочки, пока не появится подписчик

Должно быть так:
```java
contactDetailsInteractor.loadDetailsContact(id)
  .subscribeOn(Schedulers.io())
  .observeOn(AndroidSchedulers.mainThread())
  .doOnSuccess(contact -> notificationInteractor.onBirthdayNotification(contact))
  .doFinally(() -> result.finish())
  .subscribe();
```

2020-07-01 15:28 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'junit:junit:4.12'
Если удалять эту имплементацию, то ничего не работает.

2020-07-01 15:29 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'org.mockito:mockito-core:2.28.2'
Если писать testImplementation, а не implementation, то он не видит мокито, почему так

2020-07-01 18:58 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'junit:junit:4.12'
Решил вроде как

2020-07-01 18:58 UTC, KalimullinIlnaz commented on MyApplication/java/build.gradle
> +    implementation 'org.mockito:mockito-core:2.28.2'
Решил вроде как

2020-07-02 04:18 UTC, goblinr requested changes
Еще не хватает интеграционных тестов. Нужно протестировать презентер.

2020-07-02 04:18 UTC, goblinr commented on MyApplication/java/src/test/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModelTest.java
> +        GregorianCalendar birthdayDate = new GregorianCalendar(1990, Calendar.SEPTEMBER, 8);
По условиям, день рождения должен быть 29 февраля

2020-07-02 04:18 UTC, goblinr commented on MyApplication/java/src/test/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModelTest.java
> +        GregorianCalendar testTriggerDate = new GregorianCalendar(1999, Calendar.SEPTEMBER, 8);
Дата срабатывания напоминания должна быть 2000г. 29 февраля по условиям

2020-07-02 04:18 UTC, goblinr commented on MyApplication/java/src/test/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModelTest.java
> +        GregorianCalendar testTriggerDate = new GregorianCalendar(2000, Calendar.FEBRUARY, 29);
Похоже ты перепутал условия с предидущим тестом

2020-07-02 16:56 UTC, goblinr requested changes

2020-07-02 16:56 UTC, goblinr commented on MyApplication/library/build.gradle
> +    implementation('junit:junit:4.13')
`testImplementation`

2020-07-02 16:56 UTC, goblinr commented on MyApplication/library/src/androidTest/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenterTest.java
> +                new CurrentTimeModel(),
Это тоже нужно замокать, иначе твои тесты будут привязаны к тому времени, в которое они запускаются.

2020-07-02 16:56 UTC, goblinr commented on MyApplication/library/src/androidTest/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenterTest.java
> +    public void setNotification() {
Название теста ничего не говорит о том, как должна работать функция и что тестируется в ней

2020-07-02 16:56 UTC, goblinr commented on MyApplication/library/src/androidTest/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenterTest.java
> +    public void getStatusToggleButton() {
Не говорящие название теста

2020-07-02 16:56 UTC, goblinr commented on MyApplication/library/src/androidTest/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/presenters/ContactDetailsPresenterTest.java
> +    public void removeNotification() {
Название теста

2020-07-03 04:12 UTC, goblinr approved these changes

2020-07-03 08:29 UTC, merged