CodeStyle
KalimullinIlnaz/AndroidLessons pull request #17
Opened 2020-07-03 17:58 UTC by KalimullinIlnaz

Автоматизация проверки Code Style, статический анализ кода и финальное причесывание проекта

2020-07-04 04:49 UTC, goblinr commented
- [x] Требуется внедрить в проект автоматическую проверку Code Style и поправить все предупреждения
- [ ] Требуется настроить Android Lint и поправить все предупреждения
- [ ] Настроить статический анализатор кода PMD и поправить все его предупреждения. 
- [ ] Настроить CI на основе Travis CI

2020-07-04 13:41 UTC, goblinr requested changes

2020-07-04 13:41 UTC, goblinr commented on MyApplication/gradle.properties
> +org.gradle.java.home=C:\\Program Files\\Java\\jdk-14
Такие вещи не должны попадать в репозиторий. Это плохо, т.к. привязывает твой проект к конкретным путям и к конкретным ОС. Используй `JAVA_HOME` на локальной машине для таких вещей

2020-07-04 14:02 UTC, goblinr commented
Запустил проверки на своей машине:
checkstyle - не проходит Unable to create Root Module: config {/config/check/rules-checkstyle.xml}
pmd - находит ошибки в java модуле

2020-07-04 23:19 UTC, KalimullinIlnaz commented
Некоторые предупреждения pmd можно игнорировать по типу view = null в onDestroyView и большого числа импорта пакетов во фрагменте?

2020-07-05 04:36 UTC, goblinr commented
> Некоторые предупреждения pmd можно игнорировать по типу view = null в onDestroyView и большого числа импорта пакетов во фрагменте?

Игнорировать ничего не стоит. Все эти правила не спроста появились, следует подумать - как произвести рефакторинг, что бы убрать эти предупреждения

2020-07-05 04:40 UTC, goblinr commented
По поводу обнуления вьюшек - обрати внимание на такую библиотеку https://jakewharton.github.io/butterknife (особенно удели внимание разделу BINDING RESET)

2020-07-05 15:10 UTC, KalimullinIlnaz commented
Pmd говорит " Found non-transient, non-static member. Please mark as transient or provide accessors." к презентеру фрагмента, сделать его transient или статик я не могу получается нужно прописать get и set к презентеру во фрагменте это разве правильный вариант?

2020-07-05 15:50 UTC, goblinr commented
> Pmd говорит " Found non-transient, non-static member. Please mark as transient or provide accessors." к презентеру фрагмента, сделать его transient или статик я не могу получается нужно прописать get и set к презентеру во фрагменте это разве правильный вариант?

Конкретно в этом случае, это предупреждение следует проигнорировать. Можно добавить добавить исключение на эту ошибку в `pmd-rules.xml` на все поля помеченные `@InjectPresenter`

2020-07-06 03:59 UTC, goblinr requested changes

2020-07-06 03:59 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/AppModule.java
> +    private final transient Application application;
`transient` - здесь не нужен. Если на это ругается PMD - то можно подавить это предупреждение

2020-07-06 03:59 UTC, goblinr commented on MyApplication/application/src/main/java/com/a65apps/kalimullinilnazrafilovich/application/app/AppDelegate.java
> +    private transient AppComponent appComponent;
`transient` - здесь не нужен. Если на это ругается PMD - то можно подавить это предупреждение

2020-07-06 03:59 UTC, goblinr commented on MyApplication/config/pmd/rules-pmd.xml
> +    </rule>-->
Думаю, это просто можно удалить

2020-07-06 03:59 UTC, goblinr commented on MyApplication/java/build.gradle
> +
Не хватает блока настройки PMD

2020-07-06 03:59 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/BirthdayNotification.java
> +    private final transient boolean notificationWorkStatus;
transient не нужен.

2020-07-06 03:59 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/entities/BirthdayNotification.java
> +    private final transient boolean notificationWorkStatus;
такое ощущение, что у тебя `rules-pmd` не подтягивается, т.к. в них правило  `BeanMembersShouldSerialize` отключено

2020-07-06 03:59 UTC, goblinr commented on MyApplication/java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/contacts/ContactListModel.java
> +    private final transient ContactListRepository contactListRepository;
`transient` не нужен. Разберись, почему `rules-pmd.xml` не подтягивается. И везде убери `transient`

2020-07-06 04:05 UTC, goblinr commented
У меня в проектах - такая конфигурация PMD,  с ней все работает нормально:
```groovy
apply plugin: 'pmd'

pmd {
    toolVersion = '6.8.0'
    ruleSets = []
}

task pmd(type: Pmd) {
    description 'Identifying potential problems mainly dead code, duplicated code, cyclomatic complexity and overcomplicated expressions'
    group 'verification'
    ruleSetFiles = files("$project.rootDir/tools/rules-pmd.xml")
    source = fileTree('src/main/java')
    include '**/*.java'
    exclude '**/gen/**'

    reports {
        xml.enabled = false
        html.enabled = true
        html.destination file("$project.buildDir/outputs/pmd/pmd.html")
    }
}
```
Попробуй с ней

2020-07-06 11:55 UTC, KalimullinIlnaz commented
![image](https://user-images.githubusercontent.com/63044917/86590467-562dd580-bf98-11ea-8045-79ef6ee817f2.png)
![image](https://user-images.githubusercontent.com/63044917/86590475-59c15c80-bf98-11ea-973d-35b02e9cda89.png)
Здесь стоит создавать отдельный объект?

2020-07-06 15:06 UTC, KalimullinIlnaz commented
![image](https://user-images.githubusercontent.com/63044917/86608080-bdf11a00-bfb2-11ea-806f-95e517ba44a8.png)
Здесь pmd говорит, что переменных слишком много, их много только за счет полей вьюшки получается
Есть вариант с тем, чтобы закинуть все textView в лист и обращаться по номеру элемета, но это как то нечитабельно получается, больше у меня нет вариантов как уменьшить количество переменных, возможно ли тут применить игнорирование правила?

2020-07-06 15:54 UTC, goblinr commented
> ![image](https://user-images.githubusercontent.com/63044917/86590467-562dd580-bf98-11ea-8045-79ef6ee817f2.png)
> ![image](https://user-images.githubusercontent.com/63044917/86590475-59c15c80-bf98-11ea-973d-35b02e9cda89.png)
> Здесь стоит создавать отдельный объект?

Нет, в этом случае можно подавить предупреждение

2020-07-06 16:02 UTC, goblinr commented
> ![image](https://user-images.githubusercontent.com/63044917/86608080-bdf11a00-bfb2-11ea-806f-95e517ba44a8.png)
> Здесь pmd говорит, что переменных слишком много, их много только за счет полей вьюшки получается.
> Есть вариант с тем, чтобы закинуть все textView в лист и обращаться по номеру элемета, но это как то нечитабельно получается, больше у меня нет вариантов как уменьшить количество переменных, возможно ли тут игнорировать это правило?

Вариант 1(менее предпочтительный) - воспользоваться паттерном проектирования "Делегат"
Вариант 2(более предпочтительный) - переделать этот экран на `RecyclerView` с использованием различных типов `ViewHolder` - это позволит иметь неограниченное количество телефонов и email-ов у контакта

2020-07-06 23:05 UTC, KalimullinIlnaz commented
А тогда в других фрагментах есть вариант использовать паттерн "Делегат" для избавления от предупреждения "Слишком много импортов"?

2020-07-07 03:43 UTC, goblinr requested changes

2020-07-07 03:43 UTC, goblinr commented on MyApplication/library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/fragments/ContactListFragment.java
> +    private ContactListAdapter contactListAdapter;
`contactListAdapter` нужно обнулять в `onDestroyView`

2020-07-07 03:44 UTC, goblinr commented
> А тогда в других фрагментах есть вариант использовать паттерн "Делегат" для избавления от предупреждения "Слишком много импортов"?

Да, можно

2020-07-07 03:52 UTC, goblinr commented
- [ ] Требуется внедрить в проект автоматическую проверку Code Style и поправить все предупреждения. (Остались еще не поправленные предупреждения)
- [x] Требуется настроить Android Lint и поправить все предупреждения
- [ ] Настроить статический анализатор кода PMD и поправить все его предупреждения. (Остались еще не поправленные предупреждения)
- [ ] Настроить CI на основе Travis CI

2020-07-07 14:41 UTC, KalimullinIlnaz commented
А, похоже этот файл должен быть в корне самого гитхаба, а не в папке с проектом...

2020-07-07 20:01 UTC, goblinr requested changes
Что-то поломалось в загрузчике контактов. Приложение показывает пустой список контактов.
Так же, если зайти на экран карты с пустым списком контактов - получаем крэш
```
java.lang.IllegalStateException: no included points
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:29)
        at com.google.android.gms.maps.model.LatLngBounds$Builder.build(Unknown Source:21)
        at com.a65apps.kalimullinilnazrafilovich.library.applicaiton.delegate.route.MapWorkDelegate.setMarkers(MapWorkDelegate.java:56)
        at com.a65apps.kalimullinilnazrafilovich.library.applicaiton.fragments.RouteMapFragment.showMarkers(RouteMapFragment.java:123)
        at com.a65apps.kalimullinilnazrafilovich.library.applicaiton.views.RouteMapView$$State.showMarkers(RouteMapView$$State.java:23)
```

2020-07-07 20:01 UTC, goblinr commented on java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/location/ContactLocationModel.java
> +    private final transient LocationRepository locationRepository;
transient - не нужен

2020-07-07 20:01 UTC, goblinr commented on java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/notification/NotificationModel.java
> +    private final transient GregorianCalendar birthdayGregorianCalendar;
Убрать transient

2020-07-07 20:01 UTC, goblinr commented on java/src/main/java/com/a65apps/kalimullinilnazrafilovich/interactors/route/RouteModel.java
> +    private final transient GeocodeRepository geocodeRepository;
transient

2020-07-07 20:01 UTC, goblinr commented on library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/activity/MainActivity.java
> +    @RequiresApi(api = Build.VERSION_CODES.M)
От этого нужно избавиться.

2020-07-07 20:01 UTC, goblinr commented on library/src/main/java/com/a65apps/kalimullinilnazrafilovich/library/applicaiton/activity/MainActivity.java
> +    @RequiresApi(api = Build.VERSION_CODES.M)
Это нужно убрать

2020-07-07 20:39 UTC, KalimullinIlnaz commented
Странно, у меня показывает контакты и на реальном устройстве и на эмуляторе.

2020-07-08 07:45 UTC, goblinr requested changes
Баг не поправлен. У меня в списке контактов есть контакт без телефонного номера, и это приводит к тому, что у тебя курсор крэшится при попытке получить телефон, что приводит к пустому списку контактов.
Также следует проверить контакты без email

2020-07-08 09:25 UTC, goblinr approved these changes

2020-07-08 09:27 UTC, merged