HomeWork
KalimullinIlnaz/AndroidLessons pull request #3
Opened 2020-04-27 14:10 UTC by KalimullinIlnaz

Добавлено:
-- ContactListFragment - фрагмент со списком контактов
---- Короткая карточка контакта
------ Фотография контакта
------ Имя контакта
------ Телефон контакта
При клике пользователя на карточку контакта происходит переход на фрагмент деталей контактов. Необходимо в аргументах передавать ID выбранного контакта
-- ContactDetailsFragment
---- Фотография контакта
---- Имя контакта
---- Телефон контакта
---- 2-й телефон
---- e-mail контакта
---- 2-й e-mail контакта
---- Описание контакта
При нажатии на кнопку назад происходит возвращении с деталей контакта на список контактов.
Каждый фрагмент меняет заголовок в Toolbar: ContactListFragment -> "Список контактов", ContactDetailsFragment -> "Детали контакта"
colorPrimary" = #cb4256
colorPrimaryDark = colorPrimary
colorAccent = #4A988C
![1](https://user-images.githubusercontent.com/63044917/80381649-e9b49d00-88a9-11ea-9bf8-636c966f933e.PNG)
![2](https://user-images.githubusercontent.com/63044917/80381652-eae5ca00-88a9-11ea-9a6f-dc165cda617a.PNG)

2020-04-27 15:29 UTC, goblinr requested changes

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +        return inflater.inflate(R.layout.fragment_contact_details, container, false);
В требованиях к ДЗ нужно передавать ID контакта в этот фрагмент в аргументах.

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    private ContactDetailsFragment contactDetailsFragment;
Это опасная практика - держать ссылку на фрагмент, даже внутри другого фрагмента, т.к. жизненные циклы фрагментов могут не совпадать. В данном случае `ContactListFragment` живет дольше чем `ContactDetailsFragment` т.к. остается в бэкстеке. В случае возвращения с `ContactDetailsFragment` по кнопке "Назад" - произойдет утечка памяти выделенной под этот фрагмент, т.к. на него есть жесткая ссылка  здесь.

Почитай про то как работает сборщик мусора в Java. Тебе станет понятнее о чем я говорю.

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    private FragmentTransaction fragmentTransaction;
Ссылку на `FragmentTransaction` тоже не имеет смысла держать здесь

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +        linearLayout = (LinearLayout)view.findViewById(R.id.person);
Ссылку на `linearLayout` необходимо обнулить в `onDestroyView` иначе будет утечка памяти выделенной под View. Это все опять же к тому как работает GC в Java и как это соотнести с жизненным циклом фрагмента

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +                contactDetailsFragment = new ContactDetailsFragment();
Нужно передать в аргументы ID контакта

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +    ContactListFragment contactListFragment;
Не храни ссылки на фрагмент. Это прямой путь к утечкам памяти.
Либо обнуляй ссылку в `onDestroy`

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +    FragmentTransaction fragmentTransaction;
Не храни ссылку на `FragmentTransaction`

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +        fragmentTransaction.commit();
Здесь возможна такая ситуация:
После поворота экрана - `ContactListFragment` добавится еще раз и их будет уже 2 и так далее.
Необходимо сделать так:
```Java
if (savedInstanceState == null) { // мы точно запускаем Activity в первый раз
        contactListFragment = new ContactListFragment();
        fragmentManager = getSupportFragmentManager();
        fragmentTransaction = fragmentManager.beginTransaction();
        fragmentTransaction.add(R.id.container,contactListFragment);
        fragmentTransaction.commit();
}
```

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +    <LinearLayout
Лишняя вложенность:
единственный `LinearLayout` внутри другого `LinearLayout`

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +                android:id="@+id/imageView2"
Названия id View должны отражать суть данных, которые эта View будет отображать
`imageView2` и тому подобные названия - не годятся.
Это касается всех разметок в твоем проекте

2020-04-27 15:29 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +        android:padding="7dp"
нечетные размеры могут привести к проблемам на некоторых устройствах, старайся их избегать
Это касается всего проекта

2020-04-29 03:36 UTC, goblinr requested changes

2020-04-29 03:36 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/Contact.java
> +    private String description;
`final` ко всем полям

2020-04-29 03:36 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +            android:id="@+id/text1"
Непонятное название id

2020-04-29 03:36 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_details.xml
> +            android:id="@+id/text2"
Непонятное название id

2020-04-29 03:36 UTC, goblinr commented on MyApplication/app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Бесполезная вложенность 2-х `LinearLayout`. Один `LinearLayout` можно убрать

2020-04-29 09:10 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/Contact.java
> +    private String description;
А зачем их делать final?
В "телефонной книге" всегда можно было менять эти поля.

2020-04-29 09:13 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/Contact.java
> +    private String description;
Хорошая практикой в Java мире - использовать неизменяемые объекты в качестве Data Transfer Objects(DTO). Про преимущества и недостатки таких объектов можешь почитать у Джошуа Блоха в Effective Java

2020-04-29 16:16 UTC, goblinr approved these changes

2020-04-29 16:55 UTC, merged