ContactService
KalimullinIlnaz/AndroidLessons pull request #4
Opened 2020-05-06 16:18 UTC by KalimullinIlnaz

Написал привязанный сервис предоставляющий список контактов

2020-05-06 17:26 UTC, goblinr requested changes

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    private ContactService contactService = new ContactService();
Нет, это так не работает. Инстанс привязанного сервиса можно получить только через `ServiceConnection`. Т.е. разработчик не вправе сам создавать инстанс сервиса, за него это делает система.

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    class LoadingContact extends AsyncTask<Void,Void,Void> {
Здесь утечка памяти. Почитай про сборщик мусора и про корневые объекты. Чтобы побороть эту утечку - посмотри в сторону вложенных(а не внутренних) классов и слабых ссылок. Подсказка, утечка будет происходить на время смены конфигурации активности(например при повороте экрана) и если работа потока будет долгой.

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    class LoadingContact extends AsyncTask<Void,Void,Void> {
Также советую работу с многопоточностью вынести в сервис из фрагмента.

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    private ContactService contactService = new ContactService();
Здесь тоже самое, см. комментарий выше

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    class LoadingContacts extends AsyncTask<Void,Void,Void> {
Утечка памяти

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    class LoadingContacts extends AsyncTask<Void,Void,Void> {
Вынести работу с потоками в сервис

2020-05-06 17:26 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +        bindService(intent,serviceConnection, Context.BIND_AUTO_CREATE);
советую делать это в `onCreate`
и не забывать отвязываться в `onDestroy`

2020-05-07 16:24 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    class LoadingContact extends AsyncTask<Void,Void,Void> {
Получается я как то неправильно здесь использовал слабые ссылки?

2020-05-07 16:28 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    class LoadingContact extends AsyncTask<Void,Void,Void> {
Да. И не только это. Почитай про различия между внутренними и вложенными классами в Java,  и ты поймешь, что у тебя здесь не верно сделано еще.

2020-05-08 14:16 UTC, goblinr requested changes

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    private ContactService contactService = new ContactService();
Не исправлено

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +        contactDetails = contactService.getDetailContact(id);
Контакты необходимо загружать асинхронно. В данном месте происходит блокирование главного потока программы

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +        contacts = contactService.getListContacts();
Блокирование главного потока программы

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    }
Ты не верно понял ДЗ. На отдельном потоке нужно **загружать** а не создавать контакты

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    }
Этот метод должен быть асинхронным

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    }
Этот метод должен быть асинхронным

2020-05-08 14:16 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +            addFragmentListContact();
Фрагмент нужно добавлять только когда активность создается впервые. Сейчас же, при пересоздани и активности - фрагмент добавится 2-й раз

2020-05-09 14:05 UTC, goblinr requested changes

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +    View viewContactDetails;
Ссылку на view нужно обнулять в `onDestroyView()`

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +            viewContactDetails.post(new Runnable() {
Прежде чем обращаться к view, следует проверить, что она еще не уничтожена

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
здесь тоже самое, следует проверить, что view еще не уничтожена сначала.

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +    private View view;
Обнулять в `onDestroyView`

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +        ((MainActivity) getActivity()).getSupportActionBar().setTitle("Список контактов");
к `MainActivity` приводить не нужно `getSupportActionBar()` есть у `AppCompatActivity`

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +           view.post(new Runnable() {
Проверять view на null

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    public Contact getDetailContact(ContactDetailsFragment.GetContact callback, int idContact){
сделай возвращаемый тип `void`

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    public Contact[] getListContacts(ContactListFragment.GetContact callback){
сделай возвращаемый тип `void`

2020-05-09 14:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +        if (savedInstanceState == null) firstCreateMainActivity = true;
`firstCreateMainActivity = savedInstanceState == null`

2020-05-09 14:24 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
То есть проверять каждую TextView?

2020-05-09 14:31 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
С большой долей вероятности, если одна из view null, то и все остальные то же, т.к. они все должны обнулиться тобой в `onDestroyView`, поэтому можно проверить и сделать `return`

2020-05-09 14:32 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
Но а так да - проверять надо все

2020-05-09 14:38 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
Получается и в контактлисте также нужно проверять?

2020-05-09 14:39 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
Да

2020-05-09 14:40 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +        if (savedInstanceState == null) firstCreateMainActivity = true;
это короткая запись данной строки моей строки как я понимаю?

2020-05-09 14:41 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +        if (savedInstanceState == null) firstCreateMainActivity = true;
верно

2020-05-09 15:42 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
if (listItem == null) listItem = getLayoutInflater().inflate(R.layout.fragment_contact_list, null, false);
Так а эта проверка в ContacList разве не та которая нужна нам?

2020-05-09 15:43 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    TextView name = (TextView)viewContactDetails.findViewById(R.id.name);
Нет

2020-05-10 03:44 UTC, goblinr approved these changes

2020-05-10 08:59 UTC, merged