BroadcastReceiver
KalimullinIlnaz/AndroidLessons pull request #5
Opened 2020-05-14 13:16 UTC by KalimullinIlnaz

Добавил к деталям контакта поле "День рождения" в формате "число месяц"

А так же кнопку которая будет иметь 2 состояния - "Включить напоминания" и "Выключить напоминания"
Состояние кнопки должно зависеть от того, добавлена ли уже задача в AlarmManager или нет.

При нажатии кнопки в состоянии "Включить напоминания" - ставиться задача на вызов  BroadcastReceiver'а на число в поле "День рождения" в качестве данных в Intent должен передаваться ID выбранного контакта и текст напоминания "Сегодня день рождения у $s", где $s - имя контакта
При нажатии кнопки в состоянии "Выключить напоминания" - производиться отмена предстоящей задачи в AlarmManager и состояние кнопки должно обновиться на "Включить напоминания"

BroadcastReceiver в свою очередь запускает Notification(Специальное уведомление, которое показывается в шторке уведомлений) с текстом пришедшем ему из Intent.

При нажатии пользователем на уведомление - запускается активность вашего приложения, при этом  сразу открывается экран с деталями контакта у которого день рождение, уведомление при этом исчезает из шторки уведомлений.

2020-05-14 17:05 UTC, goblinr requested changes

2020-05-14 17:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/BroadReceiver.java
> +                        .setContentTitle("Напоминание")
Это нужно брать из ресурсов. Упростит в будущем локализацию приложения

2020-05-14 17:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +        toggleButton.setOnCheckedChangeListener(this);
Нужно установить реальное состояние кнопки, прежде чем добавлять слушатель.
Реальное состояние нужно узнать у `AlarmManager` - добавлена ли задача на напоминание, или нет

2020-05-14 17:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +                    AlarmManager.INTERVAL_DAY * 365, alarmIntent);
Здесь скрыт баг, твой интервал не учитывает високосный год.

2020-05-14 17:05 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/MainActivity.java
> +            }
Здесь баг - `addFragmentListContact` вызывается 2 раза, в случае если мы пришли в приложение из оповещения и `firstCreateMainActivity == true`

2020-05-14 18:55 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/BroadReceiver.java
> +                        .setContentTitle("Напоминание")
Получается положить все в strings.xml?

2020-05-14 19:38 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/BroadReceiver.java
> +                        .setContentTitle("Напоминание")
Да

2020-05-15 04:05 UTC, goblinr approved these changes

2020-05-15 10:10 UTC, merged