ContactsProvider
KalimullinIlnaz/AndroidLessons pull request #7
Opened 2020-05-15 19:12 UTC by KalimullinIlnaz

Реализовал загрузку контактов пользователя из поставщика контактов

2020-05-18 05:25 UTC, goblinr requested changes

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +    private ArrayList<Contact> contacts;
Это плохая идея - кэшировать контакты в сервисе. Предоставь хранение контактов - системному поставщику контактов.

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +        loadContacts();
Так делать не стоит

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                Contact result = contacts.get(id);
Здесь тебе нужно обратиться к поставщику контактов и загрузить один контакт с определенным ID из него.

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            while (cursor.moveToNext()){
Работу с курсором следует обернуть в `try {} finally {}` и закрывать в `finally` блоке. Так нужно делать с каждым открытым курсором

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                String email = "";
У контакта может быть несколько телефонов и несколько email. Так же не вижу работу с получением дня рождения `ContactsContract.CommonDataKinds.Event.START_DATE`

2020-05-18 05:25 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                pCur.close();
как я писал выше, закрывать курсор в `finally` блоке

2020-05-18 05:26 UTC, goblinr commented
Так же, твое приложение обязано спросить пользователя разрешение на чтение контактов, прежде чем их читать.

2020-05-18 12:22 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                Contact result = contacts.get(id);
А там же id разные, то есть приходит id(номер в листе),а тут другой id нужен, как их сопоставить?

2020-05-18 12:24 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                Contact result = contacts.get(id);
В том то и дело, что тебе не нужно ориентироваться на позицию в листе - это провальная стратегия.

2020-05-18 12:27 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                Contact result = contacts.get(id);
По имени тогда искать?

2020-05-18 12:28 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                Contact result = contacts.get(id);
> По имени тогда искать?

Зачем? У тебя же есть структура `Contact` - добавь в нее строковое поле `id`, которое будет соответствовать уникальному идентификатору контакта в поставщике контактов

2020-05-18 23:25 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                String email = "";
![image](https://user-images.githubusercontent.com/63044917/82268506-d90eb880-9977-11ea-8986-d8781bc1425f.png)
Попытался запушить изменения получил эту ошибку, git pull не помог.
Может создать новый пулл реквест?

2020-05-19 04:09 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +                String email = "";
Он говорит, что у тебя есть какие-то комиты в удаленном хранилище и голова твоей локальной ветки находится не на вершине remote ветки. Это могло произойти по разным причинам, разберись по какой причине это произошло и в зависимости от ситуации - разберись с ней. Новый PR создавать категорически не нужно. Поправь все в этом.

2020-05-19 09:20 UTC, goblinr requested changes

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            cursor.close();
```java
if (cursor != null) {
    cursor.close();
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            cursor.close();
```java
if (cursor != null) {
    cursor.close();
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            email = "Почта отсутствует";
Хардкод строки

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            email2 = "Вторая почта отсутствует";
Хардкод строки

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            telephoneNumber2 = "Второй телефонный номер отсутствует";
Хардкод строки

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            birthOfDay = "Дата рождения не установлена";
Хардкод строки

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            pCur.close();
```java
if (cursor != null) {
    cursor.close();
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            while (pCur.moveToNext()) {
```java
if (cursor != null) {
...
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            while (emailCur.moveToNext()) {
```java
if (cursor != null) {
...
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            emailCur.close();
```java
if (cursor != null) {
...
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            assert dOfBirthCur != null;
```java
if (cursor != null) {
...
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            dOfBirthCur.close();
```java
if (cursor != null) {
...
}
```

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            readDataOfBirth(idContact,contentResolver);
Это плохая практика, делать методы с сайд-эффектами, лучше придерживаться подхода чистых функций, в твоем случае предполагается, что есть какое-то состояние для вызова этих функций - это плохо. Функция должна получать на вход параметры и выдавать результат, она не должна попутно менять какое-то внешнее состояние.

2020-05-19 09:20 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/BroadReceiver.java
> +        Intent intent = new Intent(Constants.BROAD_ACTION);
id контакта поменялось на String. Забыл в своем `BroadReceiver` изменить работу с намерением.

2020-05-19 09:27 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            assert dOfBirthCur != null;
assert dOfBirthCur != null; а почему данная строка не является правильным вариантом?

2020-05-19 09:36 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactService.java
> +            assert dOfBirthCur != null;
Потому что это приведет к AssertionException в случае если попался корявый провайдер и он вернул null, что в свою очередь приведет к выполнению блока `finally` где тот же самый  `assert` уже приведет к крэшу приложения

2020-05-19 09:59 UTC, goblinr requested changes

2020-05-19 09:59 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +        contactService.getDetailsContact(callback,id);
Прежде чем читать контакты, нужно спросить разрешение на это у пользователя

2020-05-19 09:59 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +        contactService.getDetailsContact(callback,id);
Это касается и фрагмента со списком контактов, так же

2020-05-19 10:29 UTC, goblinr requested changes

2020-05-19 10:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactDetailsFragment.java
> +
Нужно хотя бы вывести какое-то сообщению пользователю

2020-05-19 10:29 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/ContactListFragment.java
> +                }
Нужно хотя бы вывести какое-то сообщению пользователю если нет разрешения

2020-05-19 10:38 UTC, goblinr approved these changes

2020-05-19 10:42 UTC, merged