MVP Moxy
KalimullinIlnaz/AndroidLessons pull request #9
Opened 2020-05-23 22:44 UTC by KalimullinIlnaz

Произвел рефакторинг кода.Удалил существующий сервис загрузки контактов, и всю работу по загрузке контактов из сервиса вынес в репозиторий, который используется в Presenter.

2020-05-24 16:03 UTC, goblinr requested changes

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/adapters/ContactAdapter.java
> +        viewHolder = holder;
Какой смысл сохранять жесткую ссылку на `ViewHolder`?

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/adapters/ContactAdapter.java
> +                itemAdapterClickListener.onClick(v,getAdapterPosition());
`getAdapterPosition()` нужно проверить на `RecyclerView.NO_POSITION` прежде чем использовать.

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/adapters/ContactAdapter.java
> +    private  class ContactViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener{
Используй вложенный класс, вместо внутреннего для `ViewHolder` иначе `RecyclerView.swapAdapter` - приведет к печальным последствиям.

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +    @StateStrategyType(OneExecutionStateStrategy.class)
Зачем это здесь а не в интерфейсе? и почему `OneExecutionStateStrategy` а не `AddToEndSingleStrategy`?

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +        recyclerView.setAdapter(contactAdapter);
Это плохая практика - каждый раз пересоздавать адаптер. Нормальная практика - создавать адаптер 1 раз на время `onCreateView()` -> `onDestroyView()`, а данные в адаптер засылать через кастомный метод `setData()` например с последующим вызовом `notifyDataSetChanged()`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +    private String id;
`final`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        Contact contact = contactDetailsRepository.getDetailsContact(id);
Блокирование главного потока программы. Нужно делать чтение контакта асинхронно.

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +    private ContactListRepository contactListRepository;
`final`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        ArrayList<Contact> contacts = contactListRepository.getContacts();
Блокирование главного потока программы

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactDetailsRepository.java
> +    private ContentResolver contentResolver;
`final`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactDetailsRepository.java
> +    public Contact getDetailsContact(String idContact){
Метод должен быть асинхронным

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactListRepository.java
> +    private ContentResolver contentResolver;
`final`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactListRepository.java
> +    public ArrayList<Contact> getContacts(){
Метод должен быть асинхронным

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/ContactDetailsView.java
> +    @StateStrategyType(OneExecutionStateStrategy.class)
Эта стратегия игнорирует смену конфигурации. Используй `AddToEndSingleStateStrategy`

2020-05-24 16:03 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/views/ContactListView.java
> +    @StateStrategyType(OneExecutionStateStrategy.class)
Эта стратегия игнорирует смену конфигурации. Используй `AddToEndSingleStateStrategy`

2020-05-24 18:30 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        ArrayList<Contact> contacts = contactListRepository.getContacts();
Получается тогда через callback получать контакты?

2020-05-24 19:37 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        ArrayList<Contact> contacts = contactListRepository.getContacts();
Получается я загружаю контакты, но мой метод  getViewState().showContactList(contacts);
вызывается раньше и contacts оказывается null. Как я понимаю, я могу вызвать у потока загрузки join, но не думаю, что это правильный вариант

2020-05-24 19:55 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +        recyclerView.setAdapter(contactAdapter);
В итоге это будет выглядеть так?
contactAdapter.setData(contacts);
contactAdapter.notifyDataSetChanged();

2020-05-25 04:02 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
> +        recyclerView.setAdapter(contactAdapter);
Да

2020-05-25 04:04 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        ArrayList<Contact> contacts = contactListRepository.getContacts();
`getViewState().showContactList(contacts);` нужно вызывать **после** загрузки контактов и в главном потоке программы. Т.е. ты сначала на отдельном потоке загружаешь контакты, затем добавляешь задание на EventLooper главного потока, в котором вызываешь `getViewState().showContactList(contacts);`

2020-05-25 11:05 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        ArrayList<Contact> contacts = contactListRepository.getContacts();
Я создаю handler с Looper.getMainLooper() дальше у handler-а вызываю post и там уже вызываю метод showContactList, что не так?

2020-05-27 05:21 UTC, goblinr requested changes

2020-05-27 05:21 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/fragments/ContactListFragment.java
>          recyclerView.setAdapter(contactAdapter);
`setAdapter` каждый раз делать не нужно. Сделай его один раз в `onCreateView`

2020-05-27 05:21 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
```java
private final Handler handler = new Handler(Looper.getMainLooper());

private final GetDetails callback = new GetDetails() {
        @Override
        public void getDetails(Contact result) {
            handler.post(new Runnable() {
              @Override
              public void run() {
                  getViewState().showContactDetail(result);
              }
          });
        }
    };

public void showDetails() {
  new Thread(new Runnable() {
            @Override
            public void run() {
                contactDetailsRepository.getDetails(callback,id);
            }
        }).start();
}

public void onDestroy() {
  handler.removeCallbacksAndMessages(null);
}
```

2020-05-27 05:21 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
А вообще, на WIKI moxy есть кучу HOWTO например https://github.com/Arello-Mobile/Moxy/wiki/Simple-Async

2020-05-27 05:21 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactListPresenter.java
> +        // как дождаться выполнения этого потока не через join
см. комментарий выше

2020-05-27 07:41 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
Но asyntask же объявили устаревшим, поэтому я не стал его использовать

2020-05-27 07:44 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
Верно, я просто привел ссылку для общего понимания, как делать асинхронное взаимодействие в презенторе. За место async task можно использовать что-то другое, принцип при этом не меняется.

2020-05-27 07:48 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
Ещё такой вопрос, у меня имеется класс Constants, будет ли его правильным перенести его в ресурсы?

2020-05-27 07:53 UTC, goblinr requested changes

2020-05-27 07:53 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactDetailsRepository.java
>          new Thread(new Runnable() {
Здесь нужно решить. Либо ты запускаешь поток, на ко тором производишь IO операции в репозитории, либо в презенторе.

2020-05-27 07:53 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactListRepository.java
> +        new Thread(new Runnable() {
Тоже самое, нужно определиться - кто запускает поток загрузки данных - презентор или репозиторий.

2020-05-27 09:18 UTC, goblinr approved these changes

2020-05-27 09:18 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/presenters/ContactDetailsPresenter.java
> +        // как дождаться выполнения этого потока не через join
Нет, не стоит константы переводить в локализуемые ресурсы.

2020-05-27 09:26 UTC, merged

2020-05-27 10:35 UTC, KalimullinIlnaz commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactListRepository.java
> +        new Thread(new Runnable() {
Я отправляю запрос но получаю ответа пишет, что ключ не верен
В личном кабинете ключ активен.
В чем может быть проблема
Сам запрос:
https://geocode-maps.yandex.ru/1.x?geocode=53.215099,56.837364&apikey=Здесь мой AP Iключ из кабинета разработчика Яндекса&format=json

![image](https://user-images.githubusercontent.com/63044917/83008971-b5eea380-a01e-11ea-9211-aa002ca71bd1.png)

![image](https://user-images.githubusercontent.com/63044917/83009047-ce5ebe00-a01e-11ea-80ae-b3e50949279e.png)

2020-05-27 10:41 UTC, goblinr commented on MyApplication/app/src/main/java/com/a65apps/kalimullinilnazrafilovich/myapplication/repositories/ContactListRepository.java
> +        new Thread(new Runnable() {
Это не лучшее место для получения консультатции, либо создай draft PR с курсовой и задай вопрос в нем. Либо в classroom. 

Вообще, на сколько я помню, должно пройти некоторое время после того как ключ создан. Из документации:
"Ключ будет активирован в течение 15 минут после получения."